In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("BerlinEmo.csv",header=None)

In [7]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,6544,6545,6546,6547,6548,6549,6550,6551,6552,6553
count,535.0,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,...,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000,535.000000
mean,0.0,14.086129,118.626168,84.259813,5.329150,8.756979,-0.002953,-9.174142,2.509586,10.810209,...,207.311310,206.984164,0.327145,149.038430,42481.733271,151.002061,43050.937383,79.477038,268.528972,3.564486
std,0.0,3.555768,94.187848,123.720030,0.997456,3.412580,0.011106,1.316416,0.550829,5.218266,...,33.143113,33.239545,2.658774,22.340976,10730.371802,21.885244,10754.548593,20.563734,96.561669,2.035051
min,0.0,9.010984,11.000000,0.000000,2.736268,3.593890,-0.087758,-15.114580,1.241718,3.211274,...,108.722200,105.534900,-9.368449,95.931510,17325.020000,97.352760,17325.020000,33.816660,118.000000,1.000000
25%,0.0,12.316125,41.500000,0.000000,4.606047,7.178238,-0.007382,-9.880515,2.116135,7.679754,...,183.940950,183.622700,-1.231324,134.166500,34764.905000,136.230200,35507.940000,65.610835,196.000000,2.000000
50%,0.0,13.519070,99.000000,4.000000,5.331364,8.357074,-0.002738,-9.075601,2.472551,10.027410,...,205.618900,205.240500,0.110827,147.201700,41761.410000,149.375000,42552.880000,78.558720,251.000000,3.000000
75%,0.0,15.231700,173.000000,157.500000,5.970002,9.754961,0.002179,-8.372849,2.832590,12.661275,...,228.636250,227.903050,1.660922,164.817300,49253.580000,165.996450,50146.270000,91.550495,319.500000,5.000000
max,0.0,38.719170,777.000000,831.000000,8.485430,32.260630,0.040329,-4.592337,5.184955,55.431260,...,331.030100,339.576000,12.381900,224.695800,86168.970000,226.625400,86168.970000,142.451400,748.000000,7.000000

In [11]:
df.iloc[:,6553].max()

7.0

In [12]:
df.iloc[:,6553].min()

1.0

In [13]:
df.iloc[:,6553].mean()

3.5644859813084113